### ISSUE TITLE
AssertionError: point_labels must be supplied if point_coords is supplied.

### ISSUE THREAD

**Issue by stupworker** [facebookresearch/segment-anything#101]
img = Image.open("./demo_jpg/huang.jpg")
imgArray = np.array(img)

predictor.set_image(imgArray)

masks, _, _ = predictor.predict("./demo_mask")

# I dont know why it doesnt work...

**Comment by domenicoml** [comment]
I found the same assertion error.

**Comment by xiaoliujapan** [comment]
me too

**Comment by HannaMao** [comment]
There are a few examples in this [notebook](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/predictor_example.ipynb) showing how to provide point_labels and point_coords as inputs to the predict() function.

**Comment by zyh040521** [comment]
same

**Comment by xinkangzhou** [comment]
input_point = np.array([[451, 255]])
input_label = np.array([1])
//The coordinates and coordinates of the point serve as the front background

**Comment by nikhilaravi** [comment]
Please follow the instructions in the demo notebook and reopen the issue if you still have problems.
