### ISSUE TITLE
Simple static mask drawer, supporting SAM point-prompt

### ISSUE THREAD

**Issue by lujiazho** [facebookresearch/segment-anything#116]
This is for a simple demo of SAM. More features of box-prompt, segment everything, etc. will be added.

https://github.com/lujiazho/SegDrawer

![demo](https://user-images.githubusercontent.com/68451409/230734765-02d7981e-1c39-43a6-b2bf-f3b09941b854.gif)
![demo1](https://user-images.githubusercontent.com/68451409/230752199-bb011fdc-572f-44f4-8900-adf543dcd0b5.gif)
![demo2](https://user-images.githubusercontent.com/68451409/231078614-7c195b1a-0080-4274-9082-f63ea8b8d07f.gif)

Cut-offs download
![image](https://user-images.githubusercontent.com/68451409/231358575-bab11a8b-f4b8-4395-af82-ef600c98724f.png)

**Comment by kadirnar** [comment]
This is great project.  How did you write the draw code?

**Comment by lujiazho** [comment]
All frontend is in static web code: html, css, and javascript!

**Comment by kadirnar** [comment]
> All frontend is in static web code: html, css, and javascript!

I couldn't find the javascript code. Did you just use html and css? I don't know js,css but I want to develop interface for this project. Can I just do it with css and fastapi?

My Project:  https://github.com/kadirnar/segment-anything-video

**Comment by lujiazho** [comment]
It's all in one file with internal js and CSS. FastAPI is for providing backend server, frontend could be in HTML with CSS and js. You can also develop interface for your project in Python PyQt

**Comment by nikhilaravi** [comment]
Here is our official front end only mini demo of how to run the onnx model in the browser: https://github.com/facebookresearch/segment-anything/tree/main/demo
