### ISSUE TITLE
will this code allow us to run the application and site as the demo site locally?

### ISSUE THREAD

**Issue by jadedgnome** [facebookresearch/segment-anything#12]
will this code allow us to run the application and same site as the demo site locally?

**Comment by profinger** [comment]
It doesn't seem to contain the web interface and the outputs I'm getting differ from what the demo is doing for the same image.  I'm working on tweaking parameters to try to get the same outputs but it'd be nice if they just published what the settings were for the demo.

**Comment by MiscellaneousStuff** [comment]
Source code of the Meta SAM site demo: https://github.com/MiscellaneousStuff/meta-sam-demo

**Comment by prathamjagga** [comment]
does not seem to do so!

**Comment by nikhilaravi** [comment]
Hi @jadedgnome this is the official example of how to run the onnx model in the browser: https://github.com/facebookresearch/segment-anything/tree/main/demo. Please see the README.md in the demo folder for more details.
