### ISSUE TITLE
Image embeddings in the browser

### ISSUE THREAD

**Issue by kevmo314** [facebookresearch/segment-anything#14]
It seems like the ONNX colab example, while technically in the browser, requires generating the image embeddings and `POST`s the image to https://model-zoo.metademolab.com/predictions/automatic_masks

Is it possible to get the image embeddings via the SAM predictor in the browser as well? I guess that model is quite large so it has to be done on the server? Or perhaps I misunderstood the approach?

**Comment by Luxcy** [comment]
hello, what is https://model-zoo.metademolab.com/predictions/automatic_masks?
And about what is about  its official website?
Thanks!

**Comment by kevmo314** [comment]
@Luxcy I've managed to reproduce the server code, it simply runs the vision transformer and then spits out the embeddings as a base64-encoded string. https://github.com/kevmo314/magic-copy/blob/main/server-example/app.py

**Comment by zekikos** [comment]
I think its about model size(as you said). Can't reduce model size to be used in browsers etc.

**Comment by Luxcy** [comment]
> @Luxcy I've managed to reproduce the server code, it simply runs the vision transformer and then spits out the embeddings as a base64-encoded string. https://github.com/kevmo314/magic-copy/blob/main/server-example/app.py

Thanks. I get it!

**Comment by Luxcy** [comment]
> @Luxcy I've managed to reproduce the server code, it simply runs the vision transformer and then spits out the embeddings as a base64-encoded string. https://github.com/kevmo314/magic-copy/blob/main/server-example/app.py

Thanks. I get it!

**Comment by nikhilaravi** [comment]
This is our official demo of how to run the onnx model in the browser: https://github.com/facebookresearch/segment-anything/tree/main/demo

Please see the README.md in the demo folder for more details on how to run the webapp.
