### ISSUE TITLE
STREETS dataset selection question

### ISSUE THREAD

**Issue by rhfeiyang** [facebookresearch/segment-anything#143]
For STREETS dataset(https://databank.illinois.edu/datasets/IDB-3671567), I am confused about which one you used for evaluating zero-shot segmentation with point prompts? Thanks.
![image](https://user-images.githubusercontent.com/99195158/230843899-05d789bd-0274-4670-9876-664761bab9e6.png)

**Comment by lauragustafson** [comment]
We used the data in `vehicleannotations.zip`, which contains images and instance segmentation masks for the vehicles.
