### ISSUE TITLE
How to split the picture？

### ISSUE THREAD

**Issue by liujiadong369** [facebookresearch/segment-anything#144]
<img width="1219" alt="b" src="https://user-images.githubusercontent.com/33118274/230849598-5d1610d9-c8c7-4baf-bc30-45ea61d19329.png">
Could you please tell me whether there is such demo case that the right side is divided into the left side in the picture display？

**Comment by liujiadong369** [comment]
Cut out all objects

**Comment by liujiadong369** [comment]
Is this feature in your demo that I can't find on your GitHub? Is it written separately or how is it implemented?

**Comment by kukukakakeikei** [comment]
I also want to know

**Comment by nikhilaravi** [comment]
Please see this tutorial notebook on how to generate the automatic mask predictions for an image: https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/automatic_mask_generator.py

**Comment by liujiadong369** [comment]
How to break it up into big chunks? For example, a house is a whole person and it's a person who doesn't have to separate arms and feet @nikhilaravi

**Comment by liujiadong369** [comment]
Is there anything that takes only the parameters of the body, which means you just give it the right range of parameters

@nikhilaravi

**Comment by liujiadong369** [comment]
Why is there only a dozen images in your slice? The default value I used was more than 50 after he cut the image. Do you need to change those parameters? @likethesky

**Comment by liujiadong369** [comment]
I don't want it to cut so much at once, so can I change some parameters to make it cut less and still keep the main body intact

@nikhilaravi

**Comment by gtangg12** [comment]
Opening this again since this was never addressed
