### ISSUE TITLE
Enable SAM's text prompts with OVSeg

### ISSUE THREAD

**Issue by Jeff-LiangF** [facebookresearch/segment-anything#154]
For anyone who is interested,

Feel free to try our demo: SAM + OVSeg at https://huggingface.co/spaces/facebook/ov-seg

TL, DR: We enable SAM's text prompts with mask-adapted CLIP, achieving fine-grained open-vocabulary segmentation!!!

Check out our CVPR 2023 paper OVSeg for more details: https://jeff-liangf.github.io/projects/ovseg/

**Comment by Eli-YiLi** [comment]
https://github.com/xmed-lab/CLIP_Surgery

This is our work about CLIP's explainability. It's able to guide SAM to achieve text to mask without manual points. 

Besides, it's very simple without any fine-tuning, using the CLIP model itself only. 

Furthermore, it enhances many open-vocabulary tasks, like segmentation, multi-label classification, multimodal visualization. 

This is the jupyter demo:
https://github.com/xmed-lab/CLIP_Surgery/blob/master/demo.ipynb

![fig4](https://user-images.githubusercontent.com/49093246/231662220-2b91306c-4dc8-42d1-9fdd-3fbbafadeb26.jpg)
