### ISSUE TITLE
What is the recommended size for video memory

### ISSUE THREAD

**Issue by bouyeijiang** [facebookresearch/segment-anything#160]
OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.82 GiB total capacity; 2.49 GiB already allocated; 27.69 MiB free; 2.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by nikhilaravi** [comment]
Please provide more details of what you are trying to do including the code to reproduce the error.

**Comment by bouyeijiang** [comment]
i just running the example notebooks  in the projects,changing to use CPU is ok.

the example automatic_mask_generator_example.ipynb
error code line in
masks2 = mask_generator_2.generate(image)

**Comment by widedh** [comment]
Hello, I have the same issue. Did you find a solution? Thank you

**Comment by bouyeijiang** [comment]
There is a temporary solution, which is to first use the minimum model and then control the pixel size of the image,suggested around 500x500
