### ISSUE TITLE
有没有c++的api接口呀

### ISSUE THREAD

**Issue by pww1971** [facebookresearch/segment-anything#165]

**Comment by nikhilaravi** [comment]
Please provide more details in English for us to be able to assist.

**Comment by qiantubu** [comment]
没有C++接口，你可以试试导出onnx以后，用C++能否调用·

**Comment by SonwYang** [comment]
> 没有C++接口，你可以试试导出onnx以后，用C++能否调用·

It is hard to write inference code about prompt.
