### ISSUE TITLE
How to change the colour of the mask

### ISSUE THREAD

**Issue by stupworker** [facebookresearch/segment-anything#183]
Here is my outcome.
![image](https://user-images.githubusercontent.com/108318655/231468522-2b031398-f18d-42d7-81c4-b627d8ede755.png)
I want to get a white and black jpg, what can i do? Thanks!!!!

**Comment by JordanMakesMaps** [comment]
The mask doesn't have a color. You're using something like matplotlib which is providing the default yellow (1) and purple (0) cmap. The mask is only a single binary channel, with 1 being where something is. If you want black and white, just do this:

```python
mask[mask == 1] =255
plt.imsave(arr=mask, fname="mask.jpg")
```

**Comment by stupworker** [comment]
Excuse me, where should i put the code in? I put them  after function save_mask_data(output_dir, masks, boxes_filt, pred_phrases) in grounded_sam_demo.py, but it does not work...

**Comment by stupworker** [comment]
> The mask doesn't have a color. You're using something like matplotlib which is providing the default yellow (1) and purple (0) cmap. The mask is only a single binary channel, with 1 being where something is. If you want black and white, just do this:
> 
> ```python
> mask[mask == 1] =255
> plt.imsave(arr=mask, fname="mask.jpg")
> ```
Excuse me, where should i put the code in? I put them after function save_mask_data(output_dir, masks, boxes_filt, pred_phrases) in grounded_sam_demo.py, but it does not work...

**Comment by Nomination-NRB** [comment]
> > The mask doesn't have a color. You're using something like matplotlib which is providing the default yellow (1) and purple (0) cmap. The mask is only a single binary channel, with 1 being where something is. If you want black and white, just do this:
> > ```python
> > mask[mask == 1] =255
> > plt.imsave(arr=mask, fname="mask.jpg")
> > ```
> 
> Excuse me, where should i put the code in? I put them after function save_mask_data(output_dir, masks, boxes_filt, pred_phrases) in grounded_sam_demo.py, but it does not work...

You can use this repo: https://github.com/Nomination-NRB/SAM-webui
