### ISSUE TITLE
min_mask_region_area not working correctly

### ISSUE THREAD

**Issue by Rz1010** [facebookresearch/segment-anything#187]
I created a new mask generator:

```
mask_generator_2 = SamAutomaticMaskGenerator(
    model=sam,
    points_per_side=32,
    pred_iou_thresh=0.86,
    stability_score_thresh=0.92,
    crop_n_layers=1,
    crop_n_points_downscale_factor=2,
    min_mask_region_area=600000,  # Requires open-cv to run post-processing
)
```

My image generated 39 masks with min_mask_region_area=100 with the maximum mask being 64000 second max is around 3000. The parameter min_mask_region_area works weirdly as setting the value to 600000 results in 35 masks, which is not logical. Looking into the source to try to find why...

**Comment by Rz1010** [comment]
Could be solved easily after mask generation, 

# Specify the minimum and maximum area value you want to filter by
min_area = 6000
max_area = 30000

new_dict = []

for i in masks:
    if i['area'] > min_area and i['area'] < max_area:
        new_dict.append(i)

#Now new_dict is your new mask

**Comment by HannaMao** [comment]
Please see code [here](https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/utils/amg.py#L287-L289) for detailed implementation.

**Comment by DaniyarGilimov** [comment]
I was facing with the same issue, didn't find any solution, but SAM2 min_mask_region_area works properly so i migrated from SAM to SAM2
