### ISSUE TITLE
inference in C++?

### ISSUE THREAD

**Issue by julinfn** [facebookresearch/segment-anything#190]
I got the onnx model of SAM,but i don't know how to use this onnx model in C++ for interactive label. is there C++ API or any demo?

**Comment by SpencerWhitehead** [comment]
Hello, we do not provide a C++ interface. Please see our Python implementation (https://github.com/facebookresearch/segment-anything#getting-started) as well as the front-end-only mini demo for running the ONNX model in the browser (https://github.com/facebookresearch/segment-anything/tree/main/demo).

**Comment by mlruns** [comment]
> I got the onnx model of SAM,but i don't know how to use this onnx model in C++ for interactive label. is there C++ API or any demo?

couldn't we use onnxruntime to run exported onnx model and inference in c++?

**Comment by dinglufe** [comment]
Here a C++ version inference (use onnxruntime), which exports the preprocessing operations of Segment Anything as another onnx model. https://github.com/dinglufe/segment-anything-cpp-wrapper

**Comment by qnmts** [comment]
> 我得到了 SAM 的 onnx 模型，但我不知道如何在 C++ 中使用这个 onnx 模型作为吸引力标签。有 C++ API 或任何演示吗？



> 我得到了 SAM 的 onnx 模型，但我不知道如何在 C++ 中使用这个 onnx 模型作为吸引力标签。有 C++ API 或任何演示吗？

hello， Have you solved the problem？
