### ISSUE TITLE
Is the SAM encoder (pre-trained MAE) further trained?

### ISSUE THREAD

**Issue by lweitkamp** [facebookresearch/segment-anything#193]
I was wondering if the encoder, which is a MAE ViT-B to ViT-L, was trained further during the training of SAM. In other words, is SAM trained end-to-end, or is the encoder frozen? It was not directly clear from the paper.

**Comment by HannaMao** [comment]
SAM is trained end-to-end.

**Comment by seann999** [comment]
I assume this means the encoder was fine-tuned from MAE initialization? Was there an ablation comparing this with random initialization? I couldn't find it in the paper.
