### ISSUE TITLE
In SA-1B, how are polygons with holes represented in annotation?

### ISSUE THREAD

**Issue by levan92** [facebookresearch/segment-anything#195]
For example, 

<img width="262" alt="image" src="https://user-images.githubusercontent.com/13159336/231725245-cca2eb00-9f16-40a2-a9b1-c7975344d520.png">

I note that polygon with holes isn't exactly supported in COCO JSON format/RLE format: https://github.com/cocodataset/cocoapi/issues/153

**Comment by HannaMao** [comment]
Please see [here](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/mask.py) for descriptions of COCO RLE format.

**Comment by levan92** [comment]
Ah right okay, RLE encoding encodes from binary masks directly instead of from polygons. Thanks!

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, you can drag & drop the COCO RLE JSON file of the SA-1B dataset to the labels table to import mask annotations.

[Segment Anything 1 Billion (SA-1B)](https://ai.meta.com/datasets/segment-anything-downloads/) is a dataset designed for training general-purpose object segmentation models from open world images.

![dragDropRLEJSONFilesXML](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/c15b6458-9dfa-44f1-94e7-320e306a4554)

**Comment by ryouchinsa** [comment]
Improved "Create polygon using SAM" feature so that you can label pixels using the pixels option. You can label [Segment Anything 1 Billion (SA-1B)](https://ai.meta.com/datasets/segment-anything-downloads/) like dataset by yourself.

![sam-pixels](https://github.com/facebookresearch/segment-anything/assets/1954306/d828c18b-6fda-4258-b866-21bc34a0d17f)

**Comment by MihaiDavid05** [comment]
Hi, I have build [this](https://github.com/MihaiDavid05/Mask-to-COCO-JSON) mask exporter that also preserves the holes when exporting, using the RLE format. Have a look if you wish.
