### ISSUE TITLE
Demo Remove Area

### ISSUE THREAD

**Issue by simi-chen** [facebookresearch/segment-anything#207]
"I would like to ask about how the "Remove Area" feature works on a demo website, and how it is implemented using a script. Is it achieved through a simple mask subtraction, or is there something else going on? Could you please advise?"

**Comment by Jordan-Pierce** [comment]
Once you determine the mask of the area you want to remove, you can use the bounding box provided with opencv or even numpy to remove that area from the image (making it all black, 0 values), or crop it out from the original image and save it.

```python
sub_image = np.zeros(shape=image.shape[0:2], dtype=np.uint8)
sub_image = image[mask] # gives you just the region of interest within the image, the rest of image is black

# if you want just the area of interest, not the entire image, use bbox
x1, y1, x2, y2 = bbox
sub_image = mask[y1:y2, x1:x2]
```

**Comment by SpencerWhitehead** [comment]
Thanks @huxycn and @Jordan-Pierce ! Yes, please see the notebook for an example of using background points: https://github.com/facebookresearch/segment-anything/blob/main/notebooks/predictor_example.ipynb
