### ISSUE TITLE
SAM + SAHI for small object detection and segmentation

### ISSUE THREAD

**Issue by kadirnar** [facebookresearch/segment-anything#208]
Web Demo:  https://huggingface.co/spaces/ArtGAN/Segment-Anything-Video
Github: https://github.com/kadirnar/segment-anything-video
SAHI:  https://github.com/obss/sahi

**Comment by SpencerWhitehead** [comment]
Thanks for sharing!

**Comment by ksugar** [comment]
Hi @kadirnar, it looks amazing!
Do we need some additional processes (e.g., upsampling) to deal with small objects?
Or, can we just apply bounding boxes from SAHI to SAM?
Thanks!

**Comment by kadirnar** [comment]
You can try here. For small objects you should use SAHI library. You don't need anything else.

https://huggingface.co/spaces/ArtGAN/Segment-Anything-Video

**Comment by happyeungin** [comment]
Can it be used for only identifying the biggest object
