### ISSUE TITLE
bbox in generated mark format?

### ISSUE THREAD

**Issue by maheshs11** [facebookresearch/segment-anything#213]
the generated bbox in class SamAutomaticMaskGenerator is what format?

bbox (list(float)): The box around the mask, in XYWH format.
               area (int): The area in pixels of the mask.

XY - center of mask.
or 
xy - top left.

converted it from xywh to xyxy and drew on image it is showing bbox above segment not on segment.

**Comment by HannaMao** [comment]
xy is the coordinate of the top left corner.
