### ISSUE TITLE
Napari integration of SAM for 2D/3D images with everything/semantic/instance seg mode -> Here

### ISSUE THREAD

**Issue by Karol-G** [facebookresearch/segment-anything#214]
Hey all,

We created an integration of SAM for the python-based scientific image viewer Napari. We already extended SAM quite a bit and enable the user to:

- Use SAM's everything mode
- Click-based semantic segmentations
- Click-based instance segmentations
- Segment 2D and 3D images with SAM

This is the repo: [https://github.com/MIC-DKFZ/napari-sam](https://github.com/MIC-DKFZ/napari-sam)

It would be nice to get some feedback and suggestions for further extensions as we think that Napari + SAM is a great way to make image annotation more efficient :)

Best,
Karol

**Comment by SpencerWhitehead** [comment]
Thanks for sharing!
