### ISSUE TITLE
no keyword to describe object in prompts of dataset

### ISSUE THREAD

**Issue by beefsoup18** [facebookresearch/segment-anything#225]
Does the json prompts have no keyword to describe what each object is?
I don't found any keyword in the json prompts of SAM's dataset

**Comment by SpencerWhitehead** [comment]
We provide class-agnostic mask annotations. Please see the [dataset page](https://ai.facebook.com/datasets/segment-anything/) and the [README](https://github.com/facebookresearch/segment-anything#dataset) for more details.
