### ISSUE TITLE
Any possibility to use Segment Anything Model (SAM) for annotation class name based on color palette in the original images.

### ISSUE THREAD

**Issue by engrkhurramshabbir** [facebookresearch/segment-anything#228]
Any possibility to use Segment Anything Model (SAM) for annotation class name based on color palette in the original images.

        0: (202,150,150), # Class 1
        1: (198,186,100), # Class 2
        2: (167,183,186), # Class 3
        3: (255,255,133), # Class 4
        4: (192,192,206), # Class 5
        5: (32,80,160), # Class 6
        6: (193,134,1) # Class 7 etc.

**Comment by SpencerWhitehead** [comment]
Hello, SAM predicts class-agnostic masks, so the mask colors in the visualizations+code we provide are not meant to indicate object classes. Please see these other issues, which may be helpful: #155 #234 #49
