### ISSUE TITLE
[SAM-webui] - A simple tool for using SAM

### ISSUE THREAD

**Issue by derekray311511** [facebookresearch/segment-anything#233]
Hi! I just release a simple webui for the Segment Anything Model.  
There are positive point / negative point / boxes prompts and auto inference to be used!
Feel free to try it.

This is my small project and it's my first time to write a webui.  
If you have any question or suggestion, you can post it on my issue. Thanks!  

https://github.com/derekray311511/SAM-webui

<img src="https://user-images.githubusercontent.com/84118285/232520114-e737f6f7-55d5-465c-b7b7-8c15059e8384.gif" width="600"/>
<img src="https://user-images.githubusercontent.com/84118285/232520000-6606629d-f375-4fe7-b88f-b08f0eb64321.gif" width="600"/>
<img src="https://user-images.githubusercontent.com/84118285/232520088-47c8879a-2c0f-45cf-aa1e-acd5a6a8591a.gif" width="600"/>

**Comment by SpencerWhitehead** [comment]
Thanks for sharing!
