### ISSUE TITLE
segmentation of persons 

### ISSUE THREAD

**Issue by AouatifZ** [facebookresearch/segment-anything#234]
Thank You for Creating the Segment Anything Model that very helpful

i have a question about how to make inferences in my custom images to predict only the masks of the 'persons' class  (for each person in the  image ) without creating point coordinate or bounding boxes 

any suggestions Please

**Comment by akashAD98** [comment]
@AouatifZ you need to use object detection, first detect the object & pass to SAM ,Here is similar thing im working on

https://github.com/akashAD98/YOLOV8_SAM

**Comment by AouatifZ** [comment]
@akashAD98 

thank you, Very helpful
