### ISSUE TITLE
Saving masks in .jpg or .png format.

### ISSUE THREAD

**Issue by Subhajyotidas** [facebookresearch/segment-anything#238]
I was experimenting with the provided notebooks, the mask are being generated properly.
Issue is, I am not being able to save the masks from notebook, in an image format which later can be read by opencv for further processing.
Is there any way to save the masks in .jpg or .png format?

**Comment by OroChippw** [comment]
Hello, I have the same doubt, do you know the solution, thank you~😁

**Comment by eyildiz-ugoe** [comment]
Same here. I am surprised that authors did not provide this in the notebook file.

**Comment by Runzhi354** [comment]
I noticed you closed this issue, how did you solve it.

**Comment by Subhajyotidas** [comment]
The masks for every object are being saved separately in an array. Create a black image of the same shape and keep doing bitwise or with every image. Then before saving change the format to CV_8UC1 and save it.

**Comment by Runzhi354** [comment]
> The masks for every object are being saved separately in an array. Create a black image of the same shape and keep doing bitwise or with every image. Then before saving change the format to CV_8UC1 and save it.

I tried to use CV2 to solve this problem, but ran into some difficulties. Can you show your code implementation?
