### ISSUE TITLE
source code for fontend https://segment-anything.com/demo?

### ISSUE THREAD

**Issue by hungtooc** [facebookresearch/segment-anything#239]
thanks for a great new model, Meta.
Can you share React source code for https://segment-anything.com/demo?

**Comment by HIMANSHUSINGHYANIA** [comment]
print("PyTorch version:", torch.__version__)
print("Torchvision version:", torchvision.__version__)
print("CUDA is available:", torch.cuda.is_available())

from segment_anything import sam_model_registry
import numpy as np

model_checkpoint = '/path/to/sam_vit_b_01ec64.pth'
sam = sam_model_registry["vit_b"](checkpoint=model_checkpoint).to(device='cuda')

images = np.zeros((10, 256, 256, 3), dtype='uint8')

batched_input = []
for i in range(images.shape[0]):
    batched_input.append(
        {
            'image': torch.as_tensor(images[i], device=sam.device).permute(2, 0, 1).contiguous(),
            'original_size': images[i].shape[:2],
        }
    )

**Comment by SpencerWhitehead** [comment]
Here is our official front-end only mini demo of how to run the onnx model in the browser with multithreading: https://github.com/facebookresearch/segment-anything/tree/main/demo

Please read the instructions in the README in the demo folder for instructions on how to run the webapp and update the image and embeddings.

**Comment by juan-jurado** [comment]
I have tried the Demo and discovered that it only allows segmenting depending on the hover of the mouse. How can I add the other functionality like the ones in the demo? Hover over and click Multi-Mask Mode, Box, and Segment All?
