### ISSUE TITLE
Can I run it in video/real-time?

### ISSUE THREAD

**Issue by rkz98** [facebookresearch/segment-anything#240]
Can I run it in video/real-time? Or just in images for now?

**Comment by rkz98** [comment]
Like OVIS: http://songbai.site/ovis/index.html#visualization

**Comment by akashAD98** [comment]
@rkz98 you can run  it on realtime /video also, first you need to detect the object, use object detector & pass that detected object frame by frame .

**Comment by bhack** [comment]
Take a look at https://github.com/z-x-yang/Segment-and-Track-Anything

**Comment by dakoner** [comment]
No, this cannot be run in real time (at least not more than about 5-10 FPS).  Every video frame needs to have a heavyweight image feature detector run first, before the segmenter runs.  Even on an A100, the feature detector takes some 150ms per image.

**Comment by hungtooc** [comment]
Yes, checkout https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once. they combine models together to solve problem
