### ISSUE TITLE
Get object category for each mask

### ISSUE THREAD

**Issue by RRighart** [facebookresearch/segment-anything#245]
I am trying out SAM using the following notebook.
https://github.com/facebookresearch/segment-anything/blob/main/notebooks/automatic_mask_generator_example.ipynb .
This works well and gives me nicely multiple segmentation masks for each image that I upload.  
I was wondering if it is possible to obtain object categories for each mask, for example using classification by an imagenet model.
As per the example in the notebook, this would give for the light blue mask "dog", for the darkgreen mask "jeans" or "leg".
Thank you very much in advance!

**Comment by SpencerWhitehead** [comment]
Hi, SAM predicts class-agnostic masks. Please see these other issues, which may be helpful: #155 #234 #49

**Comment by Maddy12** [comment]
How were the metrics in Table 5 calculated then? Are these values just for the accuracy of matching the prompted labels with the objects? How do you actually run the prompting? I do not easily see the code for this.
