### ISSUE TITLE
Is it possible to run onnx model on react native?

### ISSUE THREAD

**Issue by hungtooc** [facebookresearch/segment-anything#264]
Is it possible to run onnx model on react native?
thanks

**Comment by hungtooc** [comment]
Yes it is, we can run inference with input image embedding. but it still slow for me (5s with model_scale 500x300)

**Comment by OroChippw** [comment]
> Yes it is, we can run inference with input image embedding. but it still slow for me (5s with model_scale 500x300)

Hello, do you encounter the problem that the operator set of version 17 is not supported? If you transfer to onnx successfully, can you share it with me? Thanks https://github.com/facebookresearch/segment-anything/issues/295

**Comment by CriusFission** [comment]
> 

Is it possible to generate embeddings on device?

**Comment by OroChippw** [comment]
> > 
> 
> @hungtooc Is it possible to generate embeddings on device?

You can try to decouple the encoder and decoder to deploy according to your hardware device

**Comment by CriusFission** [comment]
> 

@OroChippw Thanks for the quick reply. I'm new to ONNX models. I want to use the model in a react application. So, do I have to convert the encoder and decoder separately to ONNX?
