### ISSUE TITLE
Weird output with specific images using ONNX decoder

### ISSUE THREAD

**Issue by hoangle2112** [facebookresearch/segment-anything#265]
Running inference using provided encoder and onnx decoder (exported from provided model by onnx_model_example.ipynb notebook).

Input image:
![night-sky](https://user-images.githubusercontent.com/124480444/233624674-212e5a01-2736-4b28-97cf-7ea894214572.jpg)

The result:

![image](https://user-images.githubusercontent.com/124480444/233624765-07e8ed1d-ce89-428e-bef1-6e567f6c206d.png)

It seems like the model recognized the correct shape, but somehow distorted the mask. Inference on images in the notebooks/ folder works fine.

**Comment by theodu** [comment]
hi @hoangle2112,
I had the same issue, I think that it might be linked to #130 or #56. An fix has been made, you can try to pull the repo and re-export your onnx model

**Comment by vietanhdev** [comment]
Check out this package for model conversion and inference code with ONNX: https://github.com/vietanhdev/samexporter.
The inference code here can solve the problem.
