### ISSUE TITLE
The result coordinates are wrong, and the coordinates do not correspond to the position

### ISSUE THREAD

**Issue by liujiadong369** [facebookresearch/segment-anything#274]
![yuan](https://user-images.githubusercontent.com/33118274/233815979-6315f7ab-ac18-4d14-8fae-ca97ae5635b4.png)
![result](https://user-images.githubusercontent.com/33118274/233815981-f6060388-0745-4b78-a163-84d3a6895746.png)
![2](https://user-images.githubusercontent.com/33118274/233815983-1268c708-ab7d-45cc-bcd0-6116bb31e2d6.jpg)

The position of xywh in csv box corresponding to the original picture is not accurate, so it does not correspond to the position of the original picture. May I ask how to solve this?

**Comment by canbaoburen** [comment]
I have the same question. Have you solved it?
