### ISSUE TITLE
register_buffer error

### ISSUE THREAD

**Issue by usstduan** [facebookresearch/segment-anything#281]
When I run the 'predictor_example.ipynb' and load the pre-trained model, it always gives me an error shown below:
     46         self.register_buffer("pixel_mean", torch.Tensor(pixel_mean).view(-1, 1, 1), False)
     47         self.register_buffer("pixel_std", torch.Tensor(pixel_std).view(-1, 1, 1), False)
     48 

TypeError: register_buffer() takes 3 positional arguments but 4 were given

I didn't change anything, so what's wrong here?

**Comment by usstduan** [comment]
Induced by pytorch version

**Comment by wqtwjt1996** [comment]
@usstduan Can you tell me what the right version of Pytorch to use? I used Pytorch with the 1.8 version and met the same issue.

**Comment by wqtwjt1996** [comment]
@usstduan Hi I just fixed this issue by reinstalling pytorch, torchaudio and torchvision using **pip** instead of **conda**. And here is the version that I used:

python 3.9.1
torch 1.10.1+cu111
torchaudio 0.10.1+cu111
torchvision 0.11.2+cu111
numpy 1.23.1
