### ISSUE TITLE
Performance of CNN-based Segmentation Model using SA-1B

### ISSUE THREAD

**Issue by Jayden9912** [facebookresearch/segment-anything#297]
Hi. May I know has anyone try to train any CNN-based segmentation model using the dataset SA-1B?
I am curious what will be its performance in particular the zero-shot generalization.

**Comment by ryouchinsa** [comment]
[The Fast Segment Anything Model(FastSAM)](https://github.com/CASIA-IVA-Lab/FastSAM) is a CNN Segment Anything Model trained using only 2% of the SA-1B dataset published by SAM authors.

**Comment by Jayden9912** [comment]
That's cool. Thanks.
