### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [facebookresearch/segment-anything#3]
Hi :wave: 

Thanks for the amazing work. I was wondering if there is a way to download the dataset.

Thanks.

Best regards,

Fra

**Comment by AntonioConsiglio** [comment]
In the paper there is the website, https://segment-anything.com/ and in the website there is the link for download thw dataset : https://ai.facebook.com/datasets/segment-anything/.

If you download it let me know.

**Comment by FrancescoSaverioZuppichini** [comment]
I am sorry, I must be blind but I cannot see a link to download the dataset on the website

**Comment by liuxy1103** [comment]
https://scontent-nrt1-1.xx.fbcdn.net/m1/v/t6/An8MNcSV8eixKBYJ2kyw6sfPh-J9U4tH2BV7uPzibNa0pu4uHi6fyXdlbADVO4nfvsWpTwR8B0usCARHTz33cBQNrC0kWZsD1MbBWjw.txt?ccb=10-5&oh=00_AfCyB7Icjme5eKJOWOHvK70QI6PTtWlk9symqgMGYyrWJQ&oe=646D7C98&_nc_sid=fb0754
I have download one of these links, but I wonder how to use this file with more than 10 GB. What's it data organization
