### ISSUE TITLE
Misspell in README.md

### ISSUE THREAD

**Issue by kingsring** [facebookresearch/segment-anything#32]
# Getting Started
or generate masks for an entire image:
`from segment_anything import build_sam, SamAutomaticMaskGenerator`
`mask_generator = SamAutomaticMaskGenerator(build_sam(checkpoint="</path/to/model.pth>"))`
`masks = mask_generator_generate(<your_image>)`

should be corrected to
masks = mask_generator`.`generate(<your_image>)

**Comment by ArslanYM** [comment]
Can i Fix this?

**Comment by ArslanYM** [comment]
@kingsring You can close the issue , its been fixed. 
![fixed](https://user-images.githubusercontent.com/104521101/230444469-d13d78d2-de76-4c87-b4f9-947b64aa4087.png)
