### ISSUE TITLE
Error in running demo

### ISSUE THREAD

**Issue by dkhanna511** [facebookresearch/segment-anything#321]
Hi, Thanks for the great work! I am trying to run the demo in localhost as mentioned in the respository. However I'm having trouble installing the dependencies using `yarn`

When I run the command `yarn && yarn start`, I get the following error:

`error npyjs@0.4.0: The engine "node" is incompatible with this module. Expected version "^12.20.0 || >=14.13.1". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

The whole prompt is as follows:
`yarn install v1.22.19
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning image-webpack-loader > imagemin-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning image-webpack-loader > imagemin-webp > exec-buffer > tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] Fetching packages...
error npyjs@0.4.0: The engine "node" is incompatible with this module. Expected version "^12.20.0 || >=14.13.1". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
(particle-tracking) dheerajk@JZ-machine:~/bowl-particles-tracking/segment-anything/demo$ `

**Comment by mfproto** [comment]
Solved by upgrading node `nvm install node` .
