### ISSUE TITLE
Can SAM generate masks and bboxes simutaneously with input prompts? 

### ISSUE THREAD

**Issue by Colezwhy** [facebookresearch/segment-anything#379]
Using SAMAutomaticMaskGenerator  cannot receive input prompts, but it can generate bboxes.
And  if using SAMPredictor, though it can receive inptut prompts, there seems no code for generating masks with bboxes?
Or how can i change the code for generating bbox with input prompts?

**Comment by 0vl0** [comment]
You can get the bounding box of the output mask. 
You can see an example an code in my answer to issue #381.

**Comment by Colezwhy** [comment]
> You can get the bounding box of the output mask. You can see an example and code in my answer to issue #381.

Thank you for help! I've finished it earlier.

**Comment by skydh** [comment]
how to work,can you tell me,thank you
