### ISSUE TITLE
meaning of the output bounding box from SamAutomaticMaskGenerator

### ISSUE THREAD

**Issue by jimmyflycv** [facebookresearch/segment-anything#42]
great job!

I found that the SamAutomaticMaskGenerator api will produce masks as well as some bounding boxes.
i guess does the bounding box stands for unknown classes?
since my dataset is private, cant uploaded here.

**Comment by jimmyflycv** [comment]
sorry. i just take annotated image as input.
close it.

**Comment by jvpassarelli** [comment]
Wrote a [simple example notebook ](https://github.com/jvpassarelli/sam-clip-segmentation/blob/main/ZeroShotSegmentAnything.ipynb) that shows how you could assign classes you choose to the bounding boxes. This labeling is from CLIP. Hope this is helpful!

**Repo**: https://github.com/jvpassarelli/sam-clip-segmentation
