### ISSUE TITLE
Is there 'binary mask' version of the mask JSON file instead of the COCO RLE format.

### ISSUE THREAD

**Issue by CVRS-CJH** [facebookresearch/segment-anything#424]
When I parsed each JSON file in the dataset, I found that doing mask. decode for each mask was time-consuming, taking approximately 100-200ms per mask, which made the processing time for each image unbearable.

**Comment by hd24007** [comment]
you need png format? 

but you need to know that:

png format is nearly impossible, since there are many points which belong to two or more instances

eg, a point on a car, it may refer to the entire vehicle body, or simply vehicle window, so one channel png is unable to deal with it. if you use multiple-channel file, that will no longer be 1-channel png, but .npy file or something else, but take huge storage

**Comment by msverma101** [comment]
hui, could you please reopen this issue.
i also want to use SAM to segment and catagorize them in a json format

something like this from the segmenation format for garment

{
  "item2": {
    "segmentation": [
      [
        232.29572649572654, 34.447388414055126, 237.0364672364673,
        40.57084520417861, 244.9377018043686, 47.089363722697165,
        252.04881291547974, 49.65726495726508, 262.5179487179489,
        51.43504273504287, 269.233998100665, 50.447388414055204,
        277.5446343779678, 49.12725546058881, 285.64339981006657,
        46.16429249762584, 294.9273504273506, 41.22602089268754,
        299.9377967711301, 36.514245014245084, 304.67853751187084,
        30.588319088319132, 306.0612535612536, 25.65004748338083,
        307.64150047483383, 23.477207977207982, 311.19705603038943,
        ---
        ...
        ...

        30.279962013295354
      ]
    ],
    "category_id": 1,
    "category_name": "short sleeve top"
  },
  "item1": {
    "segmentation": [
      [
        201.51804815682925, 224.7401022799914, 218.41555508203712,
        227.23317707223518, 236.42109524824218, 228.89522693373104,
        ...
        ...

        188.11093117408916, 266.67907521841033, 191.15802258683155,
        250.3355849137011, 196.69818879181773, 234.82311953973982
      ]
    ],
    "category_id": 8,
    "category_name": "trousers"
  }
}
