### ISSUE TITLE
Need some help with the offline web-demo

### ISSUE THREAD

**Issue by Kjelldor** [facebookresearch/segment-anything#448]
I have cloned the Repo, and using the notebooks was a blast. I wanted to see what kind of program the web-demo would be, but after I try to install it, I keep getting the same error.

On the command `yarn && yarn start` it seems to work at first, but when fetching the packages, this happens:
![image](https://github.com/facebookresearch/segment-anything/assets/64008787/d797bbe3-4ecb-4f8c-8f4e-c39e8d43250c)

It seems like I am missing something here. Is there someone who knows what kind of 'engine node' is being talked about here? I've tried downloading a later version of the copy-webpack-plugin, but that doesn't seem to be available.

**Comment by shenjo** [comment]
Your Node.js version is too old. Upgrade to the specified version or higher as indicated in the error message.

**Comment by abinash-kumar** [comment]
@Kjelldor you need to upgrade your node version to node 14 or above.

it will fix your problem.

**Comment by Kjelldor** [comment]
Thanks for the replies, this has indeed fixed my issue! Sorry for asking such a newbie question, but thanks for answering. :)
