### ISSUE TITLE
How can I express it??

### ISSUE THREAD

**Issue by samuggi** [facebookresearch/segment-anything#45]
result :
[{'segmentation': array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False]]), 'area': 76377, 'bbox': [0, 223, 422, 309], 'predicted_iou': 1.0341997146606445, 'point_coords': [[362.5, 258.65625]], 'stability_score': 0.9911314249038696, 'crop_box': [0, 0, 800, 534]}, {'segmentation': array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,........................

How can I express it??

**Comment by CamilleMaurice** [comment]
The segmentation array express for each cluster whether pixels belong or not to that cluster. I'm not sure to understand you question.

**Comment by samuggi** [comment]
I was looking for this ! 
=========================
![image](https://user-images.githubusercontent.com/60841985/230388200-1f7161d9-ea50-41db-90be-9ad36e6702a4.png)
