### ISSUE TITLE
runONNX() running onMouseMove on the same mask in the demo

### ISSUE THREAD

**Issue by cantoramann** [facebookresearch/segment-anything#475]
I have realized that runONNX() function is called onMouseMove, even if the user is moving the mouse only within the boundaries of the current mask. Is this necessary due to some reason, or can this be optimized with custom boundary checking?

**Comment by ara-vardanyan** [comment]
Hey there @cantoramann . Did you find an implementation to run it only when the mouse moves outside the mask?

**Comment by cantoramann** [comment]
I realized that actually I want that. Even if the mouse is still in the mask, depending on its coordinates, you may get a different segmentation. If you still don't want that, then I'd the generated mask in a new image/canvas outside the DOM in a context, and do comparison for a fast solution, if satisfactory performance-wise

**Comment by ara-vardanyan** [comment]
> I realized that actually I want that. Even if the mouse is still in the mask, depending on its coordinates, you may get a different segmentation. If you still don't want that, then I'd the generated mask in a new image/canvas outside the DOM in a context, and do comparison for a fast solution, if satisfactory performance-wise

Gotcha, thanks!!
