### ISSUE TITLE
Can I get class type or just binary output?

### ISSUE THREAD

**Issue by XinyueZ** [facebookresearch/segment-anything#49]
Hey,

Is it possible to get the class type of each pixel or only the background and foreground?

**Comment by ChenWeilinx** [comment]
i also would like to know

**Comment by MollyHoo** [comment]
nobady knows...

**Comment by ganghyunnnn** [comment]
segment_anything/automatic_mask_generator.py
Line 112 ~ 116

`        assert output_mode in [
            "binary_mask",
            "uncompressed_rle",
            "coco_rle",
        ], f"Unknown output_mode {output_mode}."`

I guess there are only binary class output mode

**Comment by CJQ-CS-FD** [comment]
Yeap. You can get the class type of each mask with our annotation tool. Our Semantic Segment Anything (SSA) project provides the ability to assign category labels to each mask, including fine-grained semantic labels beyond just background and foreground. We leverage multiple segmentation methods and image captioning to extract candidate categories and assign them to each region. 

Project: Semantic segment anything
Repo: https://github.com/fudan-zvg/Semantic-Segment-Anything

**Comment by XinyueZ** [comment]
@CJQ-CS-FD reported one `[issue](https://github.com/fudan-zvg/Semantic-Segment-Anything/issues)`

**Comment by nikhilaravi** [comment]
Hi @XinyueZ, SAM does not predict classes or labels.

**Comment by jvpassarelli** [comment]
I also wanted to apply classes to the masks. So I wrote this script [simple example notebook ](https://github.com/jvpassarelli/sam-clip-segmentation/blob/main/ZeroShotSegmentAnything.ipynb) that allows you to provide classes for the boxes. This is done with CLIP. Maybe this is helpful!

**Repo**: https://github.com/jvpassarelli/sam-clip-segmentation
