### ISSUE TITLE
Creating masks for humans

### ISSUE THREAD

**Issue by Schaggo** [facebookresearch/segment-anything#493]
I am having trouble generating masks for human heads.

I am using the onnx example to automatically generate masks based on a point input located at the image center to process hundreds of images from different perspectives. 

This seems to work for about half the cases - the other half looks like this.
<img width="800" alt="image" src="https://github.com/facebookresearch/segment-anything/assets/42799099/a3e8bfd7-0ec9-445b-868b-6b18c66365fa">

Is there any information on how to better inform the model ?

**Comment by Schaggo** [comment]
solved

**Comment by den-run-ai** [comment]
@Schaggo how did you solve this?

**Comment by Schaggo** [comment]
While I scrapped the approach altogether, because also my workaround did not deliver the desired results here's how I "solved" it: First run segmentation to get the rough rectangle region of the wanted content. Then solve for background.
