### ISSUE TITLE
High memory usage during image segmentation while using SAM model.

### ISSUE THREAD

**Issue by minkvirparia** [facebookresearch/segment-anything#512]
I have created an image segmentation web app using streamlit. It takes input image from the user and gives specific object segmented image using SAM model. But during image segmentation process my Dedicated GPU memory is getting full (i.e 3.9 GB from 4 GB) and RAM (14 GB from 15.4 GB), also I have noticed some sound coming from my laptop which is like some indication. So, do anyone have any idea regarding this problem ?

Hardware Specification:
1. 16GB RAM
2. 512 GB SSD
3. 4GB Graphics Card (RTX 3050)
4. Processor: Ryzen 7 octa core AMD R7-4800H

![pic1](https://github.com/facebookresearch/segment-anything/assets/44423972/724db690-c245-44de-a884-2ac0ec9a893c)
![pic2](https://github.com/facebookresearch/segment-anything/assets/44423972/90e1d12c-6ccc-4510-80fe-abe23370075c)

**Comment by hd24007** [comment]
1. use vit-b model, vit-h is too big for your GPU
2. segment_anything/automatic_mask_generator.py, in  
class SamAutomaticMaskGenerator:          
points_per_batch: int = 64, change it to 16 or 8

**Comment by minkvirparia** [comment]
Actually I have gone with vit-l model because it was giving me better accuracy compared to vit-h and vit-b in less inference time. Also, the high memory usage problem is also resolved. Btw thank you for the suggestion.

**Comment by wdc233** [comment]
> 实际上，我选择了 vit-l 模型，因为与 vit-h 和 vit-b 相比，它在更短的推理时间内为我提供了更好的准确性。此外，还解决了内存使用率高的问题。顺便说一句，谢谢你的建议。

hello，may i ask for you about how do you resolve the issue of high memory usage, i faced the same question in my inference process using SAM
