### ISSUE TITLE
AttributeError: 'str' object has no attribute 'shape'

### ISSUE THREAD

**Issue by woshitoutouge** [facebookresearch/segment-anything#52]
successfully installed and already download ViT-H SAM model, but error occurred when running the code. Can someone help?

code:

from segment_anything import build_sam, SamPredictor 
predictor = SamPredictor(build_sam(checkpoint="sam_vit_h_4b8939.pth"))
predictor.set_image("123.jpg") 
masks, _, _ = predictor.predict("dog")

#I put .jpg and .pth under folder segment-anything#

error:

(py-1) PS D:\Code\segment-anything>  d:; cd 'd:\Code\segment-anything'; & 'C:\Users\toutouge\.conda\envs\py-1\python.exe' 'c:\Users\toutouge\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '52773' '--' 'd:\Code\segment-anything\test1.py' 
Traceback (most recent call last):
  File "d:\Code\segment-anything\test1.py", line 3, in <module>
    predictor.set_image("123.jpg")
  File "d:\Code\segment-anything\segment_anything\predictor.py", line 56, in set_image
    input_image = self.transform.apply_image(image)
  File "d:\Code\segment-anything\segment_anything\utils\transforms.py", line 30, in apply_image
    target_size = self.get_preprocess_shape(image.shape[0], image.shape[1], self.target_length)
AttributeError: 'str' object has no attribute 'shape'

**Comment by sansoy** [comment]
your image file extension is  ".jgp" should be  ".jpg"

**Comment by woshitoutouge** [comment]
@sansoy thanks but it's a typing error, and i've tried some .png image, still the same error

**Comment by uqzhichen** [comment]
I checked the predict function, seems textual prompt is not supported so far. I got this error:

AssertionError: point_labels must be supplied if point_coords is supplied.

**Comment by woshitoutouge** [comment]
@uqzhichen  Thanks!

**Comment by flypigzju** [comment]
I got the same error when I want to generate mask for a png image.

code:

_from segment_anything import build_sam, SamAutomaticMaskGenerator
mask_generator = SamAutomaticMaskGenerator(build_sam(checkpoint="D:\\AI\\SegmentAnything\\sam_vit_h_4b8939.pth"))
masks = mask_generator.generate("1.png")_

error info
  File "AppData\Local\Programs\Python\Python310\lib\site-packages\segment_anything\automatic_mask_generator.py", line 198, in _generate_masks
    orig_size = image.shape[:2]
**AttributeError: 'str' object has no attribute 'shape'**

**Comment by CamilleMaurice** [comment]
The parameter from generate function is not a string it is an image already opened. You can see it in the documentation that the function "generate" expects a np.ndarray image.
You can open your image using popular librairies such as opencv or using PIL.Image (then cast to np.array(your_pil_image)) 

Hope this helps @flypigzju
