### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by WANGSSSSSSS** [facebookresearch/segment-anything#53]
I notice that the first stage of data engine trains a vit-base model, and ablations also train a vit-base model, so is the released model pretrained on final SA-1B dataset? or just from the first stage of data engine? or some other cases?

**Comment by WANGSSSSSSS** [comment]
@bakerbunker Do you know the answer?

**Comment by HannaMao** [comment]
The released vit-b and vit-l models were trained with the final SA-1B dataset.

**Comment by GewelsJI** [comment]
> The released vit-b and vit-l models were trained with the final SA-1B dataset.

Hi @HannaMao, How do you know this?

**Comment by WANGSSSSSSS** [comment]
> 

she is author

**Comment by VGrondin** [comment]
@GewelsJI bruh she's the author lmao
