### ISSUE TITLE
how to get the same result as online demo?

### ISSUE THREAD

**Issue by LLsmile** [facebookresearch/segment-anything#536]
I cannot get the same result with [online demo](https://segment-anything.com/demo) with this repo. Do I miss anythiny important? I just follow the step in jupyter notebook.

**Comment by star9988rr** [comment]
Hi, did you get the same result with [online demo](https://segment-anything.com/demo) now?

**Comment by Mr-HanSansui** [comment]
Me too, do you solve it?

**Comment by apekshapriya** [comment]
Hi @LLsmile , were you able to solve this. I am still not able to get same result as of demo.

**Comment by ammar26627** [comment]
Hey @LLsmile @apekshapriya @PengyuanHAN @star9988rr Did any of you find the solution to this?
