### ISSUE TITLE
Release the web demo please

### ISSUE THREAD

**Issue by NicholasIrving** [facebookresearch/segment-anything#55]
The web demo is a useful tool to do much thing. Release the web demo or open source can make the project more helpful and let more people take part in the project.

**Comment by guowei-lmars** [comment]
please

**Comment by guoqi1217** [comment]
yes.web demo feel better than github 3 pth.

**Comment by MiscellaneousStuff** [comment]
Source code for the web demo: https://github.com/MiscellaneousStuff/meta-sam-demo

**Comment by lujiazho** [comment]
Here is a simple web implementation of mask drawer if interested, supporting SAM
https://github.com/lujiazho/SegDrawer

**Comment by nikhilaravi** [comment]
Here is our official front-end only mini demo of how to run the onnx model in the browser with multithreading: https://github.com/facebookresearch/segment-anything/tree/main/demo

Please read the instructions in the README in the demo folder for instructions on how to run the webapp and update the image and embeddings.

**Comment by juan-jurado** [comment]
I have tried the Demo and discovered that it only allows segmenting depending on the hover of the mouse. How can I add the other functionality like the ones in the demo? Hover over and click Multi-Mask Mode, Box, and Segment All?

**Comment by nikhilaravi** [comment]
@juan-jurado we are currently not planning to release the code for the entire web demo. 

The mini demo in this repo has the main functionality that's needed to run the onnx model which is the most complicated part -- everything else can be customized on top of this in Javascript. 

The box feature is explained in [predictor_example.ipynb](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/predictor_example.ipynb), so you can adapt this code to Javascript -- once you've got the box corners you just need to format them correctly to pass into the onnx model which is explained in the notebook. 

The "Everything" feature is also explained in [automatic_mask_generator_example.ipynb](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/automatic_mask_generator_example.ipynb) -- this will require adding a simple flask server to run the model and return all the masks.

**Comment by Duwimpuhwe** [comment]
How can I save segmented image from web demo?
