### ISSUE TITLE
ONNX model in example notebook is "prebaked" to specific aspect ratio.

### ISSUE THREAD

**Issue by EndingCredits** [facebookresearch/segment-anything#56]
As noted in the title, when using the ONNX model generated by the example notebook OR the script, it appears to be restricted to the aspect ratio given in the `orig_im_size` dummy inputs.

I am not sure if this is intended behaviour (i.e. an unavoidable limitation of the ONNX system), or a bug.

This can be observed by changing the dummy input value to e.g. `[1024, 1024]` when creating the ONNX model, OR by using a different example image with different aspect ratio. When the next section of the ONNX example notebook (`onnx_model_example.ipynb`) is run, the projected mask will not match up with the underliying image, but will be deformed by a certain amount. This is rather annoying as, since the output mask its automatically "resized" to the target image dimensions, it is a pain to get the inverse transform to get both to match up again, not to mention part of the mask is permanently clipped off.

This doesn't affect the usual predict function, or inputs, and only matters for aspect ratio, scaling both dimensions identically does not affect the result.

I'm not very familiar with the ONNX export process, but I'm going to have a dig around the docs to see if I can figure this one out, but I'll leve this here in the meantime for anyone having similar issues knows what might be the culprit.

**Comment by zdhernandez** [comment]
@EndingCredits  Is my issue the same one as yours? See: https://github.com/facebookresearch/segment-anything/issues/92

**Comment by EndingCredits** [comment]
Don't think so, sorry.

**Comment by zdhernandez** [comment]
@EndingCredits  yes, it is the same. I used images with different aspect ratios and then the bug showed up.

**Comment by sunkinux** [comment]
I used pip install segmentation-anything and found that the exported onnx model always has a fixed scale

Why not update pip's package? T_T

https://github.com/vietanhdev/samexporter/issues/4#issuecomment-1773655250
