### ISSUE TITLE
I didn't find an explanation of the options for SamAutomaticMaskGenerator!

### ISSUE THREAD

**Issue by kanbekotori** [facebookresearch/segment-anything#609]
I didn't get the meaning of these options from the segment-anything official website, not even using Google. Where can I find the meaning of these options please.
```
mask_generator_2 = SamAutomaticMaskGenerator(
    model=sam,
    points_per_side=32,
    pred_iou_thresh=0.86,
    stability_score_thresh=0.92,
    crop_n_layers=1,
    crop_n_points_downscale_factor=2,
    min_mask_region_area=100,  # Requires open-cv to run post-processing
)
```

**Comment by garymarz** [comment]
https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/automatic_mask_generator.py
