### ISSUE TITLE
Decoded feature map

### ISSUE THREAD

**Issue by Lzyin** [facebookresearch/segment-anything#639]
Hi, thanks for your great work!

Can I obtain the decoded feature map, which is the same size as the input image?

I sincerely hope to get your reply.

**Comment by Lzyin** [comment]
Thanks for your reply!

Is it possible to get feature maps that are the same size as the original image after decoding? I ran the code and found that the output mask maps for different regions are all the same size as the original image.

**Comment by heyoeyo** [comment]
The mask decoder output (`raw_mask_data`) can be upscaled to whatever size you like, this is [what the SAM model does](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/predictor.py#L238C97-L238C97) to generate output masks that match the input image size. Though it does it in 2 steps to deal with how the padding works. First the 256x256 map is [scaled up](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/sam.py#L154C9-L159C10) to 1024x1024 (the image encoder input size), then the padding is removed, and then that gets [scaled to](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/sam.py#L161C9-L161C90) to the original image size.

The image embeddings could be scaled with the same sort of code (i.e. scaling the height & width of every channel of the embeddings), so you could get it to match the image size that way. However each of the 64x64 'pixels' in the image embedding encodes something about a 16x16 patch of the input image, and it's not clear that upscaling these values would give a meaningful result (though maybe still worth a try if you have some use case in mind!).

**Comment by Lzyin** [comment]
I get it, thank you very much for your reply!
