### ISSUE TITLE
Trying to understand PromptEncoder, specifically the 'points' input

### ISSUE THREAD

**Issue by dilpreetsingh** [facebookresearch/segment-anything#676]
I'm fine-tuning SAM on a custom dataset and trying to understand the Prompt Encoder a bit more thoroughly, specifically this call:
```
sparse_embeddings, dense_embeddings = sam.prompt_encoder(
    points=None,
    boxes=None,
    masks=None,
)
```
I supply the 'boxes' argument with bounding-boxes for objects i'm trying to fine-tune on, but I wanted to explore doing using the 'points' option. As I dig into this, it turns out the 'points' parameter requires a coordinate + labels tuple. But I don't understand what I'm supposed to supply as 'labels'? The model doesn't predict any classes, so i'm a bit lost on this.

**Comment by heyoeyo** [comment]
The point labels let you specify whether the points you give are meant to be 'foreground' (i.e. part of the segmentation) or 'background' (excluded from segmentation) points. Foreground points should have labels of 1 while background points have labels of 0.

There is an example of this in the [predictor notebook](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/predictor_example.ipynb), roughly half way down under the section: **Specifying a specific object with additional points**

**Comment by dilpreetsingh** [comment]
that makes sense, thank you!
