### ISSUE TITLE
官方的notebook代码报错：RuntimeError: Error(s) in loading state_dict for Sam 请问怎么解决？是权重的问题吗？

### ISSUE THREAD

**Issue by jh111222** [facebookresearch/segment-anything#69]
下面是报错详情：
RuntimeError: Error(s) in loading state_dict for Sam:
	Missing key(s) in state_dict: "image_encoder.blocks.12.norm1.weight", "image_encoder.blocks.12.norm1.bias", "image_encoder.blocks.12.attn.rel_pos_h", "image_encoder.blocks.12.attn.rel_pos_w", "image_encoder.blocks.12.attn.qkv.weight", "image_encoder.blocks.12.attn.qkv.bias", "image_encoder.blocks.12.attn.proj.weight", "image_encoder.blocks.12.attn.proj.bias", "image_encoder.blocks.12.norm2.weight", "image_encoder.blocks.12.norm2.bias", "image_encoder.blocks.12.mlp.lin1.weight", "image_encoder.blocks.12.mlp.lin1.bias", "image_encoder.blocks.12.mlp.lin2.weight", "image_encoder.blocks.12.mlp.lin2.bias", "image_encoder.blocks.13.norm1.weight", "image_encoder.blocks.13.norm1.bias", "image_encoder.blocks.13.attn.rel_pos_h", "image_encoder.blocks.13.attn.rel_pos_w", "image_encoder.blocks.13.attn.qkv.weight", "image_encoder.blocks.13.attn.qkv.bias", 。。。

**Comment by linzengmin** [comment]
#take a try
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
import cv2
sam = sam_model_registry["vit_b"](checkpoint="models/sam_vit_b_01ec64.pth")
mask_generator = SamAutomaticMaskGenerator(sam)
image = cv2.imread("images/1.png")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
masks = mask_generator.generate(image)

**Comment by linzengmin** [comment]
#take a try
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
import cv2
sam = sam_model_registry["vit_b"](checkpoint="models/sam_vit_b_01ec64.pth")
mask_generator = SamAutomaticMaskGenerator(sam)
image = cv2.imread("images/1.png")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
masks = mask_generator.generate(image)

**Comment by linzengmin** [comment]
> sam = sam_model_registry["vit_b"](checkpoint="models/sam_vit_b_01ec64.pth")

**Comment by linzengmin** [comment]
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
import cv2
sam = sam_model_registry['vit_b'](checkpoint="models/sam_vit_b_01ec64.pth")
mask_generator = SamAutomaticMaskGenerator(sam)
image = cv2.imread("images/1.png")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
masks = mask_generator.generate(image)

**Comment by linzengmin** [comment]
#take a try
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
import cv2
sam = sam_model_registry['vit_b'](checkpoint="models/sam_vit_b_01ec64.pth")
mask_generator = SamAutomaticMaskGenerator(sam)
image = cv2.imread("images/1.png")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
masks = mask_generator.generate(image)

**Comment by JinHisAndy** [comment]
> 
The error has been solved, following is the example code.
`sam_checkpoint = "weights/sam_vit_b_01ec64.pth"
    from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
    sam = sam_model_registry['vit_b'](checkpoint=sam_checkpoint)
    sam.to(device="cuda")
    mask_generator = SamAutomaticMaskGenerator(sam)

    masks = mask_generator.generate(image)`

There are some issues with the official code.

**Comment by JinHisAndy** [comment]
The error has been solved, following is the example code.
```
sam_checkpoint = "weights/sam_vit_b_01ec64.pth"
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
sam = sam_model_registry['vit_b'](checkpoint=sam_checkpoint)
sam.to(device="cuda")
mask_generator = SamAutomaticMaskGenerator(sam)
masks = mask_generator.generate(image)
```
There are some issues with the official code.
