### ISSUE TITLE
How to get the class label information corresponding to the segmentation mask area?

### ISSUE THREAD

**Issue by hh-xiaohu** [facebookresearch/segment-anything#717]
I want to know how to get the class label information corresponding to the segmentation mask area

**Comment by Matagi1996** [comment]
https://segment-anything.com/
Scroll down to FAQ and you see:
No, the model predicts object masks only and does not generate labels

But you could use a normal (weak) segmentation model that produces labels, sample points from the output to an image and feed thouse points back into SAM, than infer that the masks created have the label of the points you sampeled.

**Comment by hh-xiaohu** [comment]
> https://segment-anything.com/ Scroll down to FAQ and you see: No, the model predicts object masks only and does not generate labels
> 
> But you could use a normal (weak) segmentation model that produces labels, sample points from the output to an image and feed thouse points back into SAM, than infer that the masks created have the label of the points you sampeled.

Thanks. It's a good solution.
