### ISSUE TITLE
auto generating masks for multiple images and saving them?

### ISSUE THREAD

**Issue by martintmv-git** [facebookresearch/segment-anything#720]
### Hi,

I'm working in Colab and I'm facing an issue with generating masks for more than one image `(in fact my goal is to generate masks for my ~20k img dataset)`;

I mount my dataset from Drive, successfully reading all imgs in the folder however I can't pass the whole folder as a list for SAM to process and generate masks;

The workflow I aim for is to generate the masks and save them in a folder in my Drive;

The only working way I found to give the model more than 1 image is processing each of them separately in a loop, but as you can already guess - this isn't a good solution when talking about a rich dataset of thousands of images;

Example:

```
image_1 = cv2.imread('images/example-1.jpg')
image_2 = cv2.imread('images/example-2.jpg')
image_3 = cv2.imread('images/example-3.jpg')
...
images_list = [image_1, image_2, image_3, ... (x many images)]
results_list = [mask_generator.generate(image) for image in images_list]
```

If you are facing a similar issue or have a solution that can help my case, contact me.

**Comment by martintmv-git** [comment]
### Update,

After exploring various approaches, I've discovered a method that effectively addresses the issue I was encountering with generating masks for a large dataset in Colab.

The solution involves processing the images in batches, significantly improving efficiency when dealing with thousands of images. 

> NOTE: I noticed that for my use case, the first mask was always the best in quality, and as a result, I save only the first mask generated for each image to conserve storage space and streamline the process.

- Code cell I used, or check the notebook [here](https://github.com/martintmv-git/RB-IBDM/blob/main/Experiments/Generating%20Masks%20with%20SAM/Success%20with%20test%20dataset/sam_test_dataset_generate_masks.ipynb).

```
import cv2
from PIL import Image
import numpy as np

def save_masks_to_drive(masks, save_path, image_name):
    if masks:  # Check if there is at least one mask
        try:
            img = Image.fromarray((masks[0] * 255).astype(np.uint8))  # Use only the first mask
            mask_file_path = os.path.join(save_path, f'mask_{image_name}_0.png')  # Name for the first mask
            img.save(mask_file_path)
            print(f"Successfully saved mask to drive: {mask_file_path}")
        except Exception as e:
            print(f"Failed saving mask to drive for {image_name}: {e}")

def process_images_in_batches(dataset_path, save_path, batch_size=100):
    image_paths = [os.path.join(dataset_path, f) for f in os.listdir(dataset_path) if os.path.isfile(os.path.join(dataset_path, f))]
    for i in range(0, len(image_paths), batch_size):
        batch_paths = image_paths[i:i+batch_size]
        for path in batch_paths:
            try:
                print(f"Processing: {path}")
                image_bgr = cv2.imread(path)
                image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
                sam_result = mask_generator.generate(image_rgb)
                masks = [mask['segmentation'] for mask in sorted(sam_result, key=lambda x: x['area'], reverse=True)]
                
                # Saving only the first mask as it's the most valuable for later training
                save_masks_to_drive(masks, save_path, os.path.basename(path).replace('.jpg', '').replace('.png', ''))
                print(f"Successfully processed and saved masks for: {path}")
            except Exception as e:
                print(f"Error processing {path}: {e}")

# Process the images in batches
process_images_in_batches(dataset_path, save_path, batch_size=100)
```

**Comment by hello-world-hhh** [comment]
It looks like the SAM mask_generator is still running in a single-image manner? How long did it take you to run segmentation inference on your 20k-image dataset?
