### ISSUE TITLE
Running SAM in a loop and eventually running out of GPU memory

### ISSUE THREAD

**Issue by bthetford** [facebookresearch/segment-anything#743]
I'm using SAM to generate masks on thousands of images within a loop. Each iteration, a little bit more memory is allocated on my Nvidia GPU. It runs for a while but eventually runs out of memory.

Each iteration, I delete my model, my `SamAutomaticMaskGenerator` instance, and run `torch.cuda.empty_cache()` and `gc.collect()`, which removes a portion of the memory on the GPU, but each iteration about 1 more GB of memory is occupied. 

I also tried `numba.cuda.get_current_device().reset()`, as well as `cuda.close()`, which frees memory, but the next iteration fails.

The only way I've found to successfully clear the GPU memory is to close Python and restart again. Is there any way to use SAM continuously like this, and completely empty my GPU's memory every time?

Thanks!

**Comment by AlinGrigoras** [comment]
The solution is to use a multiprocessing approach, so you should move the image processing task to a separate process. By doing so, you isolate the memory usage of the task from the main process. This ensures that any memory consumed during processing is released back to the system when the process terminates, effectively preventing the memory leak

**Comment by bthetford** [comment]
Thanks, I did try running SAM on a separate thread using the `threading` module, but even when the thread terminated, the memory still remained allocated in the GPU. Running SAM on a `subprocess` seems to do the trick. I haven't tried the `multiprocessing` module but that could possibly work too.
