### ISSUE TITLE
Error in apply_image function? 

### ISSUE THREAD

**Issue by melisandeteng** [facebookresearch/segment-anything#754]
In the apply_image function[ here  ](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/utils/transforms.py#L26). , the expected input is HxWxC in order to use get_preprocess_shape to work. 
However to_pil_image is called on this same input but it expects CxHxW. So it seems there is a permutation of axis missing in this function between the get_preprocess_shape and to_pil_image steps?

**Comment by heyoeyo** [comment]
It's very odd code, but I think the assumption is that the input is from coming from opencv, which uses HxWxC ordering, and also BGR ordering on the channels which is accounted for when [setting the image](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/predictor.py#L52-L56).

The `to_pil_image` seems to be used specifically to match the [resize](https://pytorch.org/vision/stable/generated/torchvision.transforms.Resize.html) function requirements, which wants a shape ending in HxW and a data type of a tensor or a PIL image. Given that the function returns an np.array, it probably would've been simpler to use `cv2.resize`, but maybe they were trying to maintain consistency with some other implementation.

**Comment by melisandeteng** [comment]
Thank you @heyoeyo, you answer made me realize I had an older version of torchvision (0.15.2) for which the to_pil_image function was not compatible...
