### ISSUE TITLE
vit_b and vit_h models have same size when quantized exported to onnx

### ISSUE THREAD

**Issue by kevinshen1101** [facebookresearch/segment-anything#756]
Hello, I followed the scripts to quantize and export the various type SAM models into onnx. One thing I noticed was that after exporting, both the quantized vit_b and quantized vit_h onnx models have the same size (8.3M). Is this expected or do I have some error on my end? My (limited) understanding is that the larger parameter vit_h model should take up more storage space.

**Comment by heyoeyo** [comment]
Only the prompt encoder + mask decoder are exported in this case, and all variants of the SAM model have the same sized decoding model (though the weights have different values). But your intuition is correct, it's the image encoder (vit) that varies in size between the models, it just isn't part of the onnx export. If they were exported in a quantized format, they'd be on the order of 150MB-1000MB depending on the model size.

**Comment by kevinshen1101** [comment]
Got it, that makes sense, thanks!
