### ISSUE TITLE
How to use text as the prompt?

### ISSUE THREAD

**Issue by steven0129** [facebookresearch/segment-anything#76]
As the title, how to use text as the prompt?
According to paper, there is a way to use text the prompt. However, I didn't find any function about using text as the prompt.
![image](https://user-images.githubusercontent.com/18100669/230575154-2d5410d1-363d-4d70-8949-688991073db5.png)

**Comment by famunir** [comment]
Text cannot be used as prompt. This capability is not released. Refer to [https://github.com/facebookresearch/segment-anything/issues/4#issuecomment-1497626844](this issue).

**Comment by Imzachjohnson** [comment]
See this: https://github.com/IDEA-Research/GroundingDINO

**Comment by Eli-YiLi** [comment]
From Fig 12, the author suggest using text prompts with manual points.
Our solution is to convert text to points by explainability of CLIP:
https://github.com/xmed-lab/CLIP_Surgery

Besides, it's very simple without any fine-tuning, using the CLIP model itself only. 

Furthermore, it enhances many open-vocabulary tasks, like segmentation, multi-label classification, multimodal visualization. 

This is the jupyter demo:
https://github.com/xmed-lab/CLIP_Surgery/blob/master/demo.ipynb

![fig4](https://user-images.githubusercontent.com/49093246/231662220-2b91306c-4dc8-42d1-9fdd-3fbbafadeb26.jpg)
