### ISSUE TITLE
Question of the final masks

### ISSUE THREAD

**Issue by zkjisj** [facebookresearch/segment-anything#765]
In my understanding num_multimask_outputs mean the number of final masks, as default is 3.  I'm confused about the meaning of self.num_mask_tokens, as it is the add of num_multimask_outputs and 1. 
![image](https://github.com/facebookresearch/segment-anything/assets/88485154/835e159e-3594-464e-883c-a6b561087b33)
In the final produce of masks, the shape of output masks seems to be b*self.num_mask_tokens. After that, the postprocess_masks don't change the shape.  However, I have seen some implementations finally output 3 masks, as it is the default number of num_multimask_outputs. They take use of the predictor, and it follows the same process as sam.
![image](https://github.com/facebookresearch/segment-anything/assets/88485154/162a425e-b52d-41c7-b2b5-d73af2363520)

**Comment by heyoeyo** [comment]
The extra 4th mask (the 'zeroth' mask in the output) is used when multiple prompts are provided. You can see how it's used in the forward function of the [mask decoder](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/mask_decoder.py#L101-L105).

The [paper](https://arxiv.org/abs/2304.02643) explains this in a bit more detail in the appendix under the second paragraph of the section: **Making the model ambiguity-aware** (page 17).

**Comment by zkjisj** [comment]
@heyoeyo Thanks for your reply, It helps a lot!
