### ISSUE TITLE
What is the minimum size of graphics memory required for this model

### ISSUE THREAD

**Issue by shokosanma** [facebookresearch/segment-anything#78]
when I run demo
`python scripts/amg.py --checkpoint sam_vit_h_4b8939.pth --input download.png --output test.png`
I got this
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 5.67 GiB total capacity; 3.60 GiB already allocated; 788.38 MiB free; 3.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
so what is the minimum size of graphics memory required for this model

**Comment by CamilleMaurice** [comment]
It also depends on the size of your input_image. You can also try to reduce the value of some parameters. It works on 8Go GPU.

**Comment by liujiadong369** [comment]
Can you tell me where to set the GPU memory size?

**Comment by snoopfab** [comment]
The sam_vit_b_01ec64.pth Small model is running on my laptop with a NVidia GeForce GTX 1650 Ti 4Gi (Pretty Weak GPU and smalla mount of VRAM). While running the notebook, the memory consumption saturates the 4 Gi of VRAM and use ~6 GB of system memory
Unfortunately I was unable to run the vit_h (the default) and the medium sized  vit_l model (same error as you).
Maybe someone will release a quantized version of these models ...

**Comment by shokosanma** [comment]
> The sam_vit_b_01ec64.pth Small model is running on my laptop with a NVidia GeForce GTX 1650 Ti 4Gi (Pretty Weak GPU and small amount of VRAM). While running the notebook, the memory consumption saturates the 4 Gi of VRAM and use ~6 GB of system memory Unfortunately I was unable to run the vit_h (the default) and the medium sized vit_l model (same error as you). Maybe someone will release a quantized version of these models ...

thx, I use model `sam_vit_b_01ec64.pth` and it finished successfully.

**Comment by XuYinzhe** [comment]
> The sam_vit_b_01ec64.pth Small model is running on my laptop with a NVidia GeForce GTX 1650 Ti 4Gi (Pretty Weak GPU and small amount of VRAM). While running the notebook, the memory consumption saturates the 4 Gi of VRAM and use ~6 GB of system memory Unfortunately I was unable to run the vit_h (the default) and the medium sized vit_l model (same error as you). Maybe someone will release a quantized version of these models ...

May I ask what the size of your input image? I also use 1650Ti. My GPU out of memory even I only input image in (240, 480, 3) shape.

**Comment by widedh** [comment]
Hello, I have the same issue. Did you find a solution? Thank you

**Comment by QiangZhangCV** [comment]
> 



> The sam_vit_b_01ec64.pth Small model is running on my laptop with a NVidia GeForce GTX 1650 Ti 4Gi (Pretty Weak GPU and small amount of VRAM). While running the notebook, the memory consumption saturates the 4 Gi of VRAM and use ~6 GB of system memory Unfortunately I was unable to run the vit_h (the default) and the medium sized vit_l model (same error as you). Maybe someone will release a quantized version of these models ...

Thanks for sharing your experience. I guess transfering the .pth to onnx or inference with TensorRT engine will be less GPU memory costing and with less compution time.
