### ISSUE TITLE
Dimension Mismatch between Sparse_prompt_embedding and output_tokens

### ISSUE THREAD

**Issue by Tanishq-9001** [facebookresearch/segment-anything#797]
I am trying to train SAM for Camouflage Object Detection Task. So for a batch size other than 1, I am getting a dimension mismatch error. When I adjust it to match it with the image_embeddings and dense_prompt_embeddings then it gives mismatch with the output_tokens when I pass it through the sam.mask_decoder (which is internal in the SAM Model) and when I adjust it for output_tokens then it gives mismatch with the image_embeddings and dense_prompt_embeddings. And I cannot think of any solution to this problem
The batch size is 2

Shape of image_embeddings: torch.Size([2, 256, 64, 64])
Shape of dense_prompt_embeddings: torch.Size([2, 256, 64, 64])
Shape of sparse_prompt_embeddings: torch.Size([2, 2, 256])

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 256 but got size 2 for tensor number 1 in the list.

**Comment by MRampo** [comment]
Hello, @Tanishq-9001!  Have you found a way to solve your problem?

**Comment by annamalai-19** [comment]
@Tanishq-9001 Have you solved this problem? If so, can you explain how you solved it?
