### ISSUE TITLE
Segment Anything ?

### ISSUE THREAD

**Issue by ChaoFan996** [facebookresearch/segment-anything#80]
Great job! 
However, there appears to be a minor typo in the paper. 
Taiwan, Hong Kong, and Macau are not independent countries. 
They are all integral parts of China.
Thank you once again for delivering such a fantastic paper. 
Rectifying this error will make the paper better.
![7771680864031_ pic](https://user-images.githubusercontent.com/92680886/230595465-abebd9f3-bc80-46cd-87e7-54c6e7afb88b.jpg)

**Comment by SaifeiYan** [comment]
I strongly agree with you that they are a sacred and inseparable part of Chinese territory and that scientific research should be factual

**Comment by trougnouf** [comment]
https://en.wikipedia.org/wiki/Troll_(slang)

**Comment by Elbenhorn** [comment]
can't agree more!

**Comment by AidPaike** [comment]
can't agree more, the work is excellent, but we must respect the facts about the territorial issue, hope the author can correct it, Hong Kong, Macao, and Taiwan are inalienable parts of China.

**Comment by barrycxg** [comment]
I also can't agree more. I hope the author can correct this issue.

**Comment by relh** [comment]
I think we can resolve this github issue by checking the relevant source documentation. From the UN Charter it seems the design principle of [self-determination](https://en.wikipedia.org/wiki/Self-determination) suggests that Country classes should call internal member methods in resolving whether they are subclasses of a different Country class. To resolve this maybe we can interview someone who is Taiwanese and then make an appropriate PR as needed, not sure who to tag here.

**Comment by joe85** [comment]
It would be easier to change the word countries to regions. That maintains the specific granularity of the chart.

**Comment by yuanbovin** [comment]
> I also can't agree more. I hope the author can correct this issue.

I hope so.

**Comment by LikeRain0** [comment]
Yes. I think it's better to keep the research pure！

**Comment by qinliuliuqin** [comment]
Using "Countries/Regions" would resolve the [disputed issue](https://en.wikipedia.org/wiki/Political_status_of_Taiwan) for TWN (a province of [Republic of China](https://en.wikipedia.org/wiki/Republic_of_China_(1912%E2%80%931949)) according to its institution) and the factual error for HKG (a special administrative region of [People's Republic of China](https://en.wikipedia.org/wiki/China)).

**Comment by gorgonaut04** [comment]
> 

If you think Taiwan is part of China, why not just March your little butts over there and take it? 🤔. Like to see you try….🐓🐓🐓

**Comment by JasonChen75** [comment]
If you guys can build such datasets, you can identify Taiwan as whatever you like :)))))

**Comment by qinliuliuqin** [comment]
As suggested by @joe85, replacing "countries" with "countries/regions" in Figure 7 would circumvent the [factual error](https://www.britannica.com/story/is-hong-kong-a-country) for HKG and the [disputed issue](https://english.president.gov.tw/Page/93) for TWN. Peace and love!

**Comment by qinliuliuqin** [comment]
> > 
> 
> If you think Taiwan is part of China, why not just March your little butts over there and take it? thinking. Like to see you try….roosterroosterrooster

wow... what a brilliant anti-ballistic keyboard! You will be the only survior if there is a war.

As suggested by @joe85, the authors might consider replacing "countries" with "countries/regions" in Figure 7 to resolve the [factual error](https://www.britannica.com/story/is-hong-kong-a-country) for HKG as a country and circumvent the [disputed issue](https://english.president.gov.tw/Page/93) for TWN as another country.

**Comment by qinliuliuqin** [comment]
> https://en.wikipedia.org/wiki/Troll_(slang)
> 
> In slang, a troll is a person who posts or makes inflammatory, insincere, digressive,[1] extraneous, or off-topic messages online (such as in social media, a newsgroup, a forum, a chat room, an online video game), or in real life, with the intent of provoking others into displaying emotional responses,[2] or manipulating others' perception, thus acting as a bully or a provocateur. The behavior is typically for the troll's amusement, or to achieve a specific result such as disrupting a rival's online activities or purposefully causing confusion or harm to other people.[3]

In brief, a troll is a guy who gives :-1:  for every post he dislikes.

**Comment by qinliuliuqin** [comment]
> If you guys can build such datasets, you can identify Taiwan as whatever you like :)))))

not funny... reporting whatever you like in a paper is called a research scandal. 

I won't waste more time in this thread. Just a quick summary: HKG is not a country for sure. TWN's political status is [disputed](https://en.wikipedia.org/wiki/Political_status_of_Taiwan). It is a province of ROC under [ROC's own constitution](https://english.president.gov.tw/Page/93). If we respect these facts, we should use "countries/regions" in Figure 7 of this paper.

**Comment by julinfn** [comment]
can't agree more!

**Comment by FredmanOwen** [comment]
Honestly am just so happy i had issues with my social media accounts and needed help i couldn't get here but thanks to Twitter thread i discovered this man bohdanbohdan93 @ mail . ru who save me my business accounts.. i'm super  happy if you need such help i advice you reach out too him though his services are not free but affordable and effective

**Comment by ZiQiuWang** [comment]
香港，澳门，台湾都是中国领土，可以使用地区，但请不要用国家，谢谢

**Comment by binghui-z** [comment]
can't agree more! Standing up for the One-China Principle!

**Comment by youchaoqin** [comment]
Standing up for the One-China Principle!
Please Rectify the ERRORs in the paper!
香港，澳门和台湾都是中国的领土，中国的主权和领土完整不容分割！

**Comment by JJery-web** [comment]
Standing up for the One-China Principle!
Please Rectify the ERRORs in the paper!
香港，澳门和台湾都是中国的领土，中国的主权和领土完整不容分割！

**Comment by caoyunkang** [comment]
I also can't agree more. I hope the author can correct this issue! I am very proud of being Chinese!

**Comment by cmhungsteve** [comment]
The interesting thing is that some authors of this paper are from China.
Not sure what they think

**Comment by ChaoFan996** [comment]
This issue has aroused unnecessary political bias, thus I would like to close it.
I will directly send an e-mail to the authors.

**Comment by stonedada** [comment]
> Great job! However, there appears to be a minor typo in the paper. Taiwan, Hong Kong, and Macau are not independent countries. They are all integral parts of China. Thank you once again for delivering such a fantastic paper. Rectifying this error will make the paper better. ![7771680864031_ pic](https://user-images.githubusercontent.com/92680886/230595465-abebd9f3-bc80-46cd-87e7-54c6e7afb88b.jpg)
I will keep watching the issue !

**Comment by tanjuntao** [comment]
The authors should give a response to this issue and correct it.

**Comment by ZainZh** [comment]
支持正义

**Comment by hailin-shi** [comment]
It appears the authors closed this issue. Looking forward authors' response.

**Comment by WenOOI** [comment]
They still used the misleading world map in SAM2. This is a disrespect for China's sovereignty. The authors should correct all incorrectly used maps. This will make this work better.
